# Generated by Django 4.2.7 on 2024-01-21 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_users_alter_inventory_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='owner',
        ),
    ]
